apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260520-234612-taezx6avmivi-service
spec:
  selector:
    app: enterprise-system-20260520-234612-taezx6avmivi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
